### ISSUE TITLE
两处BUG

### ISSUE THREAD

**Issue by dreamCodeMan** [nelsonken/cos-go-sdk-v5#1]
发现5个月之前的版本两处BUG，不知道最近的更新是否有修复，未发现代码的更新，只看到readme提示

1、协程Worker中:
		err = b.UploadSlice(ctx, job.UploadID, job.Dst, job.Number, job.MD5, content)
没有对分片上传错误做处理，如果错误会造成程序退出

2、分片上传
res, err := b.conn.Do(ctx, "PUT", b.Name, dst, param, nil, content)
错误未处理，造成程序退出。

建议：在文件上传新增自定义headers

**Comment by nelsonken** [comment]
merged
