### ISSUE TITLE
请求被拒绝You must provide the Content-Length HTTP header

### ISSUE THREAD

**Issue by ioito** [nelsonken/cos-go-sdk-v5#11]
若我想做一个文件下载中转程序
下载程序使用*http.Response.Body(类型为:io.ReadCloser)作为UploadObject 的输入参数
这样依然拿不到下载文件的大小，希望可以添加自定义header字段.

**Comment by ioito** [comment]
sorry, 看到已经处理过这个问题了，不过若文件太大的话，这样处理是不是不太好

**Comment by nelsonken** [comment]
可用从 Header 里取大小
