### ISSUE TITLE
UploadObject上传一个文件，为什么content-length一直为0

### ISSUE THREAD

**Issue by kapujiang** [nelsonken/cos-go-sdk-v5#8]
`
func UploadObject() {
    bu := "kapucostest"
	ctx := cos.GetTimeoutCtx(time.Second * 30)
	objName := "img.jpg"
    f,err := os.Open("img.jpg") 
    if err != nil {
        fmt.Println(err.Error())
        return
    }
    defer f.Close()

	err = client.Bucket(bu).UploadObject(ctx, objName, f, &cos.AccessControl{})

	if err != nil {
        fmt.Println(err.Error())
	} 
}
`

输出：
Put Object:
411:请求被拒绝You must provide the Content-Length HTTP header.

**Comment by kapujiang** [comment]
这样处理能够拿到contentlength	
rc, ok := body.(io.ReadCloser)
	if !ok && body != nil {
		rc = ioutil.NopCloser(body)
	}
	req.Body = rc
	switch v := body.(type) {
	case *bytes.Buffer:
		req.ContentLength = int64(v.Len())
	case *bytes.Reader:
		req.ContentLength = int64(v.Len())
	case *strings.Reader:
		req.ContentLength = int64(v.Len())
	case *os.File:
		req.ContentLength = tryGetFileSize(v)
	}

**Comment by nelsonken** [comment]
参考：https://github.com/golang/go/issues/20257

**Comment by nelsonken** [comment]
解决了：参考 https://golang.org/pkg/net/http/#NewRequest
